version: '2'
services:
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/app.conf:delegated
    ports:
      - "8080:8080"
    environment:
      - LAGOON_ROUTE=nginx.docker.amazee.io
      - TOR_SITE=ddaqds6varcnxtwo5q4iqkfdltu5aeln57xahehkq7iwntawskmvt4qd.onion
      - TOR_SITE_PORT=443
networks:
  amazeeio-network:
    external: true