version: '2'
services:
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/app.conf:delegated
    ports:
      - "8080:8080"
    environment:
      - LAGOON_ROUTE=nginx.docker.amazee.io
    user: '10000'
networks:
  amazeeio-network:
    external: true